Support multiple tier or stack/tier workspaces
hazelops/icmk pull request #110
Opened 2021-01-15 05:00 UTC by russmac

This allows a deployment to consist of multiple "default workspaces" or paths.

The user sets either TIER or TIER & STACK to their values matching the file tree.

2021-01-15 11:21 UTC, AutomationD requested changes
Looks good, could you please provide a quick testing scenario? 
It would be great to see those three cases:
- TIER & STACK are not set
- TIER is set
- TIER & STACK are set
In all those cases, what would be the value of ENV_DIR?

A a simple `Testing Done:` section in the PR would be just fine.
like this:

```
# Features
...

# Testing Done:

$ unset TIER STACK
$ make env.debug
...

$ TIER=db make env.debug
...

$ TIER=db make env.debug
...

$ TIER=db  STACK=foo make env.debug
...
```

This test will need adding a line here https://github.com/hazelops/icmk/blob/master/main.mk#L42
```
@echo "\033[36mENV_DIR\033[0m: $(ENV_DIR)"
```

As a side note for some future,
Ideally, we could add some github jobs like this https://github.com/hazelops/icmk/blob/master/.github/workflows/tests.yml#L42 using matrix and set those vars to the respective values and run `make env.debug` and assert it somehow for test purposes.

But there is no testing framework that we have in place (yet)... Which probaby should be one single test suite and output junit xml.

2021-01-16 00:42 UTC, russmac commented
Tested with make env.debug

With $STACK and $TIER set:
`.infra/env/dev/tatango/db`

With $TIER unset:
`.infra/env/dev`

WITH $TIER set and $STACK unset:
`.infra/env/dev/db`

2021-01-19 07:42 UTC, AutomationD approved these changes

2021-01-19 09:05 UTC, AutomationD commented
It would be also good to derive TIER from `infra.<tier>` in a way similar to https://github.com/hazelops/icmk/blob/master/main.mk#L15

2021-01-23 03:21 UTC, merged