Ensures that all dependencies are installed
hazelops/icmk pull request #149
Opened 2021-06-01 14:38 UTC by igorkotof

Testing:
[![asciicast](https://asciinema.org/a/GSeUgYFQFrnCAjvu2Vj3gfoHP.svg)](https://asciinema.org/a/GSeUgYFQFrnCAjvu2Vj3gfoHP)

2021-06-01 14:42 UTC, igorkotof commented
![](https://github.trello.services/images/mini-trello-icon.png) [ICMK: Create `validate` task](https://trello.com/c/0z65hDsN/281-icmk-create-validate-task)

2021-06-20 05:58 UTC, AutomationD requested changes

2021-06-20 05:58 UTC, AutomationD commented on init.mk
> +AWS-CLI ?= $(shell which aws)
I would use an underscrore for `AWS_CLI` to keep it consistent with unix env-var naming

2021-10-04 05:25 UTC, AutomationD commented
@igorkotof any update on this? How hard would it be to fix it up the PR and wrap this up?

2021-12-06 08:43 UTC, AutomationD approved these changes

2021-12-06 08:49 UTC, AutomationD approved these changes
Looks good, thank you. just the comment cleanup.

2021-12-06 08:49 UTC, AutomationD commented on init.mk
> +#EXECUTABLES = $(GIT) $(DOCKER) aws
Should we clean this up?

2021-12-06 09:29 UTC, kobrikx approved these changes
lgtm

2021-12-07 06:21 UTC, merged