CORE-266 Default AWS tags
hazelops/icmk pull request #193
Opened 2022-01-26 19:52 UTC by igorkotof

2022-01-26 20:40 UTC, kobrikx approved these changes
lgtm

2022-01-27 08:10 UTC, AutomationD requested changes
Great solution! 

Question about name of the `env`

2022-01-27 08:10 UTC, AutomationD commented on terraform/templates/backend.tf.gotmpl
> +      environment        = "{{ .Env.ENV }}"
Should this be `env` rather?

2022-01-27 14:19 UTC, igorkotof commented on terraform/templates/backend.tf.gotmpl
> +      environment        = "{{ .Env.ENV }}"
it's up to you :) let me rename

2022-01-28 07:32 UTC, AutomationD approved these changes
Looks good.

2022-01-31 09:00 UTC, merged